version: "2"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - .:/app/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app/
