version: "3"
services:
    webapp:
        build:
            context: ./webapp
        ports:
            - "5000:5000"

    webapp-init:
        build:
            context: ./webapp-init
        ports:
            - "5002:5000"
        init: true

    webapp-exec:
        build:
            context: ./webapp-exec
        ports:
            - "5003:5000"
